### ISSUE TITLE
Speedy paths don't work

### ISSUE THREAD

**Issue by ZephaniahNoah** [NNaso/ValheimMods#5]
The mod didn't seem to do anything. So I checked `Valheim/BepInEx/LogOutput.log` and saw this.
```
[Message:   BepInEx] BepInEx 5.4.11.0 - valheim
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Linux
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2019.4.24f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [Speedy Paths Mod 1.0.5]
[Info   :AuthoritativeConfig_nex.SpeedyPaths] Initialized Server Authoritative Config Manager.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SpeedyPaths.SpeedyPathsClientMod.Awake () (at <5267be96fa0b46fd995d77ac1dfc5298>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```
As you can see I am on Linux. Perhaps that has something to do with it?

**Comment by mb0** [comment]
The plugin does a platform check and only loads assets when using windows https://github.com/NNaso/ValheimMods/blob/eac7c34ed8c9958690629bd66ccb8f71d81bcd7e/SpeedyPaths/SpeedyPaths.cs#L56 
I don't know why, maybe is meant to not load assets when running as headless server?
I set up vs code and removed the check and tried it on a linux client and it worked. I have not yet tested it on the server without the check. But if this fails on a headless server, we can probably find a better way to detect that. I could run a test and add a pull request if you think it is worth updating the plugin. Otherwise it works just fine for me. Have fun!

**Comment by ZephaniahNoah** [comment]
Try `if (UnityEngine.SystemInfo.graphicsDeviceType != GraphicsDeviceType.Null)`

**Comment by mb0** [comment]
I've just removed that check and it works fine on both client and server. I mean when you think about it, the game already consumes a lot of resources, loading a couple of images on top is not really an issue.
The hard part was setting up the environment from scratch to build the plugin. But since then I beat the game with my nephews.
I can send a pull request and/or you the build if you like.

**Comment by ZephaniahNoah** [comment]
I dropped that line into dnspy to make sure it worked. So I have a working version of the mod for Linux. Thanks

**Comment by TysonChickens** [comment]
Any update on Linux support? I tried rebuilding the plugin, but I was unable to set up the environment properly. A pull request would be appreciated.

**Comment by mb0** [comment]
pull request wouldn't do anything if not accepted. and the change is only one line removed. I'll send you an email with the build artifact, just in case. but i that requires some blind trust in me on your part. so i also include the project asset files to build it yourself.
the key insight, as far as i remember, was to use nuget to download a project template. all nuget commands in my bash history are:

    dotnet nuget update
    dotnet new -i BepInEx.Templates --nuget-source https://nuget.bepinex.dev/v3/index.json

i don't know if the update was required or where i have run the commands. maybe i have then copied the libs folder over, but idk.

**Comment by TysonChickens** [comment]
@mb0 Thank you for your assistance. I am not too familiar with Valheim modding and missed a lot resources while trying to understand them.

**Comment by NNaso** [comment]
Hey dudes, sorry for the delay.
I've been super busy and don't play Valheim much anymore, so it's taken me a while to get to this.

I've removed this check, this shouldn't really negatively affect Linux servers if they need to load 4 small textures, unity headless server may not load these anyways.

Update to 1.0.6 on Thunderstore or Nexusmods
